spring.application.name=social-platform-back

# Reduce noisy Kafka Admin/Client INFO logs when Kafka is not fully ready
logging.level.org.apache.kafka.clients.admin.internals.AdminMetadataManager=ERROR
logging.level.org.apache.kafka.clients.admin=ERROR
logging.level.org.apache.kafka=ERROR
# Keep Flink connector logs at INFO by default
logging.level.org.apache.flink.connector.kafka=INFO
